version: 2
jobs:
  build:
    docker:
      - image: golang:1.13-alpine
    working_directory: /go/src/github.com/andodevel/clock_server
    steps:
      - checkout
      - run: 
          name: "Install builing tools"
          command: apk --no-cache add bash ncurses make git gcc libtool musl-dev upx
      - run: 
          name: "Run make ci target"
          command: make ci
