version: 2.0
jobs:
  build:
    docker:
      - image: golang:1.13-alpine
    working_directory: /go/src/github.com/andodevel/clock_server
    steps:
      - checkout
      - run: 
          name: "Install builing tools"
          command: apk --no-cache add bash ncurses make git gcc libtool musl-dev upx
      - run: 
          name: "Run make ci target"
          command: make ci

  deploy:
    machine: true
    working_directory: ~/go/src/github.com/andodevel/clock_server
    steps:
      - checkout
      - run: rm -rf ~/.local/share/heroku && heroku update
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Deploy Heroku Docker Container
          command: |
            heroku container:push web --app=$HEROKU_APP
            heroku container:release web --app=$HEROKU_APP
            sleep 10 # sleep for 10 seconds to wait for dynos
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master